// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyhvkmjiialnnobvzcwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5aHZrbWppaWFsbm5vYnZ6Y3dlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3Mjg3NzgsImV4cCI6MjA2NTMwNDc3OH0.j4RblD_azLg1AM1vCEk7LbP7xUQyg_3sUau3r1si4Ks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);